set (B3D_FRAMEWORK_SOURCE_DIRECTORY ${B3D_FRAMEWORK_ROOT_DIRECTORY}/Source)
set (APP_ROOT_DIR ${B3D_FRAMEWORK_ROOT_DIRECTORY})
set (B3D_IS_ENGINE 0)

include(${B3D_FRAMEWORK_SOURCE_DIRECTORY}/CMake/Properties.cmake)
include(${B3D_FRAMEWORK_SOURCE_DIRECTORY}/CMake/FindPackageOrBuild.cmake)
include(${B3D_FRAMEWORK_SOURCE_DIRECTORY}/CMake/HelperMethods.cmake)

add_subdirectory(${B3D_FRAMEWORK_SOURCE_DIRECTORY} ${CMAKE_CURRENT_BINARY_DIR}/bsf)
