//************************************* B3D Framework - Copyright 2026 Marko Pintera *************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DRenderBeastPrerequisites.h"
#include "Renderer/B3DRendererMaterial.h"
#include "Renderer/B3DGpuUniformBuffer.h"

namespace b3d
{
	namespace render
	{
		class VisibleReflectionProbeData;
		class VisibleLightData;

		/** @addtogroup RenderBeast
		 *  @{
		 */

		B3D_UNIFORM_BUFFER_BEGIN(LightGridUniformDefinition)
			B3D_UNIFORM_BUFFER_MEMBER(Vector4I, gLightCounts)
			B3D_UNIFORM_BUFFER_MEMBER(Vector2I, gLightStrides)
			B3D_UNIFORM_BUFFER_MEMBER(i32, gNumReflProbes)
			B3D_UNIFORM_BUFFER_MEMBER(i32, gNumCells)
			B3D_UNIFORM_BUFFER_MEMBER(Vector3I, gGridSize)
			B3D_UNIFORM_BUFFER_MEMBER(i32, gMaxNumLightsPerCell)
			B3D_UNIFORM_BUFFER_MEMBER(Vector2I, gGridPixelSize)
		B3D_UNIFORM_BUFFER_END

		extern LightGridUniformDefinition gLightGridUniformDefinition;

		/** A set of buffers containing outputs from LightGrid. */
		struct LightGridOutputs
		{
			/** Uniform buffer using LightGridUniformDefinition. */
			GpuBufferSuballocation UniformBuffer;

			/**
			 * Flattened array of grid cells, where each entry contains the number of lights affecting that cell, and a index
			 * into the @p gridLightIndices buffer.
			 */
			SPtr<GpuBuffer> GridLightOffsetsAndSize;

			/**
			 * A list of light indices. Each cell's indices start at specific position and are placed sequentially one after
			 * another. Lookup into this array is done through offset & size provided by @p gridLightOffsetsAndSize.
			 */
			SPtr<GpuBuffer> GridLightIndices;

			/**
			 * Flattened array of grid cells, where each entry contains the number of reflection probes affecting that cell,
			 * and a index into the @p gridProbeIndices buffer.
			 */
			SPtr<GpuBuffer> GridProbeOffsetsAndSize;

			/**
			 * A list of reflection probe indices. Each cell's indices start at specific position and are placed sequentially
			 * one after another. Lookup into this array is done through offset & size provided by @p gridProbeOffsetsAndSize.
			 */
			SPtr<GpuBuffer> GridProbeIndices;
		};

		/**
		 * Shader that creates a linked list for each light grid cell, containing which lights and reflection probes affects
		 * each cell.
		 */
		class LightGridLLCreationMaterial : public RendererMaterial<LightGridLLCreationMaterial>
		{
			RMAT_DEF_CUSTOMIZED("LightGridLLCreation.bsl");

		public:
			LightGridLLCreationMaterial() = default;
			void Initialize() override;

			/** Binds parameter buffers and prepares any internal buffers. Must be called before Execute(). */
			void SetParams(GpuCommandBuffer& commandBuffer, const Vector3I& gridSize, const GpuBufferSuballocation& gridUniformBuffer, const SPtr<GpuBuffer>& lightsBuffer, const SPtr<GpuBuffer>& probesBuffer);

			/** Binds the material for rendering, sets up per-camera parameters and executes it. */
			void Execute(GpuCommandBuffer& commandBuffer, const RendererView& view);

			/** Returns the buffers generated by execute(). */
			void GetOutputs(SPtr<GpuBuffer>& lightsLLHeads, SPtr<GpuBuffer>& lightsLL, SPtr<GpuBuffer>& probesLLHeads, SPtr<GpuBuffer>& probesLL) const;

		private:
			GpuParameterStorageBuffer mLightBufferParam;
			GpuParameterStorageBuffer mLightsCounterParam;
			GpuParameterStorageBuffer mLightsLLHeadsParam;
			GpuParameterStorageBuffer mLightsLLParam;

			GpuParameterStorageBuffer mProbesBufferParam;
			GpuParameterStorageBuffer mProbesCounterParam;
			GpuParameterStorageBuffer mProbesLLHeadsParam;
			GpuParameterStorageBuffer mProbesLLParam;

			SPtr<GpuBuffer> mLightsCounter;
			SPtr<GpuBuffer> mLightsLLHeads;
			SPtr<GpuBuffer> mLightsLL;

			SPtr<GpuBuffer> mProbesCounter;
			SPtr<GpuBuffer> mProbesLLHeads;
			SPtr<GpuBuffer> mProbesLL;

			u32 mBufferCellCount = 0;
			Vector3I mGridSize;
		};

		/** Shader that reduces the linked list created by LightGridLLCreationMat into a sequential array. */
		class LightGridLLReductionMaterial : public RendererMaterial<LightGridLLReductionMaterial>
		{
			RMAT_DEF_CUSTOMIZED("LightGridLLReduction.bsl");

		public:
			LightGridLLReductionMaterial() = default;
			void Initialize() override;

			/** Binds parameter buffers and prepares any internal buffers. Must be called before Execute(). */
			void SetParams(GpuCommandBuffer& commandBuffer, const Vector3I& gridSize, const GpuBufferSuballocation& gridUniformBuffer, const SPtr<GpuBuffer>& lightLLHeads, const SPtr<GpuBuffer>& lightLL, const SPtr<GpuBuffer>& probeLLHeads, const SPtr<GpuBuffer>& probeLL);

			/** Binds the material for renderingand executes it. */
			void Execute(GpuCommandBuffer& commandBuffer, const RendererView& view);

			/** Returns the buffers generated by execute(). */
			void GetOutputs(SPtr<GpuBuffer>& gridLightOffsetsAndSize, SPtr<GpuBuffer>& gridLightIndices, SPtr<GpuBuffer>& gridProbeOffsetsAndSize, SPtr<GpuBuffer>& gridProbeIndices) const;

		private:
			GpuParameterStorageBuffer mLightsLLHeadsParam;
			GpuParameterStorageBuffer mLightsLLParam;

			GpuParameterStorageBuffer mProbesLLHeadsParam;
			GpuParameterStorageBuffer mProbesLLParam;

			GpuParameterStorageBuffer mGridDataCounterParam;

			GpuParameterStorageBuffer mGridLightOffsetAndSizeParam;
			GpuParameterStorageBuffer mGridLightIndicesParam;

			GpuParameterStorageBuffer mGridProbeOffsetAndSizeParam;
			GpuParameterStorageBuffer mGridProbeIndicesParam;

			SPtr<GpuBuffer> mGridDataCounter;

			SPtr<GpuBuffer> mGridLightOffsetAndSize;
			SPtr<GpuBuffer> mGridLightIndices;

			SPtr<GpuBuffer> mGridProbeOffsetAndSize;
			SPtr<GpuBuffer> mGridProbeIndices;

			u32 mBufferCellCount;
			Vector3I mGridSize;
		};

		/**
		 * Helper class that is used for generating a grid in view space, whose cells contain information about lights
		 * affecting them. Used for forward rendering.
		 */
		class LightGrid
		{
		public:
			/** Updates the light grid from the provided view. */
			void UpdateGrid(GpuCommandBuffer& commandBuffer, const RendererView& view, const VisibleLightData& lightData, const VisibleReflectionProbeData& probeData, bool noLighting);

			/**
			 * Returns the buffers containing light indices per grid cell and global grid parameters. This data gets Updated on
			 * every call to updateGrid().
			 */
			LightGridOutputs GetOutputs() const;

		private:
			GpuBufferSuballocation mGridUniformBuffer;
		};

		/** @} */
	} // namespace render
} // namespace b3d
