//************************************ B3D Framework - Copyright 2026 Marko Pintera **************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DPrerequisites.h"
#include "CoreObject/B3DRenderThread.h"
#include "Renderer/B3DRendererId.h"
#include "Utility/B3DModule.h"
#include "Allocators/B3DFrameAllocator.h"
#include "CoreObject/B3DCoreObject.h"

namespace b3d
{
	struct RendererSceneSyncData;
	class RendererScene;
	namespace ecs { class Registry; }
	namespace render { class RendererScene; }

	/** @addtogroup Renderer-Internal
	 *  @{
	 */

	/**
	 * Helper used for batch synchronization of ECS objects from the main thread into packed arrays on the render thread.
	 *
	 * Stores a contiguous array of packets containing the data to synchronize, as well as render slots which determine to which
	 * entries in the packed renderer arrays those packets should be applied to.
	 *
	 * @tparam DataType		Data type that is being synced.
	 */
	template<typename DataType>
	struct TBatchSyncBuffer
	{
		u32 Count = 0;
		u32 Maximum = 0;
		DataType* Packets = nullptr;
		RendererId* RendererIds = nullptr;

		/** Allocate internal arrays for @p count entries using @p allocator. */
		void Allocate(FrameAllocator& allocator, u32 count)
		{
			Packets = reinterpret_cast<DataType*>(allocator.AllocateAligned(sizeof(DataType) * count, alignof(DataType)));
			RendererIds = reinterpret_cast<RendererId*>(allocator.AllocateAligned(sizeof(RendererId) * count, alignof(RendererId)));

			Maximum = count;
		}

		/** Construct a new DataType in-place and store the associated renderer ID. Returns a reference to the constructed packet. */
		template<typename... Args>
		DataType& Add(RendererId rendererId, Args&&... args)
		{
			B3D_ASSERT(Count < Maximum);

			auto* packet = new(&Packets[Count]) DataType(std::forward<Args>(args)...);
			RendererIds[Count] = rendererId;
			++Count;
			return *packet;
		}

		/**
		 * Iterates entries, calling @p fn(DataType&, RendererId rendererId) for each.
		 * Destructs the packet after the callback finishes.
		 */
		template<typename Fn>
		void Each(Fn&& fn)
		{
			for(u32 entryIndex = 0; entryIndex < Count; ++entryIndex)
			{
				fn(Packets[entryIndex], RendererIds[entryIndex]);
				Packets[entryIndex].~DataType();
			}
		}

		/** Frees the frame-allocated Packets and RendererIds arrays. Must be called after Each(). */
		void Free(FrameAllocator& allocator)
		{
			if(Packets)
				allocator.Free((u8*)Packets);

			if(RendererIds)
				allocator.Free((u8*)RendererIds);
		}
	};

	/**
	 * Interface used for batch synchronization of main thread objects with their renderer-side representations.
	 * Uses ECS for fast iteration. The intention is that the caller marks dirty objects with an ECS tag,
	 * which can then be used by this system to fetch all dirty objects and store the dirty data
	 * into a frame-allocated buffer to be passed to the render thread so it can be applied there.
	 */
	class B3D_EXPORT IRendererObjectSyncHandler
	{
	public:
		virtual ~IRendererObjectSyncHandler() = default;

		/**
		 * Scans the provided registry for dirty objects, generates the update packets and stores them into a batch buffer allocated
		 * by @p allocator. Returns pointer to the batch buffer memory.
		 *
		 * @note Main thread only
		 */
		virtual void* SyncRead(ecs::Registry& registry, FrameAllocator& allocator) = 0;

		/**
		 * Applies data from a batch buffer generated by SyncRead to objects on the render thread,
		 * and frees the frame-allocated batch data via @p allocator.
		 *
		 * @note Render thread only.
		 */
		virtual void SyncWrite(void* batchData, FrameAllocator& allocator) = 0;
	};

	/**
	 * Module that orchestrates ECS-based batch sync between main thread objects and their renderer-side representations.
	 * Different types can register their own sync handlers, which are then ran every frame before kicking off
	 * render thread work.
	 *
	 * Handler registration is global (type → factory). Handler instances are owned per-scene by RendererScene,
	 * and created via CreateHandlers() during RendererScene::Initialize().
	 */
	class B3D_EXPORT RendererSyncManager : public Module<RendererSyncManager>
	{
	public:
		using HandlerFactory = Function<UPtr<IRendererObjectSyncHandler>(RendererScene&)>;

		RendererSyncManager();
		~RendererSyncManager();

		/**
		 * Run the full sync pipeline: SyncRead on main thread, queue SyncWrite operation on the render thread.
		 * If @p swapBuffers is true, rotate the frame allocator ring buffer.
		 */
		void SyncToRenderThread(bool swapBuffers);
	private:
		struct SceneSyncFrameData
		{
			render::RendererScene* RenderScene;
			RendererSceneSyncData* BatchData;
		};

		struct PerFrameSyncData
		{
			FrameAllocator* Allocator = nullptr;
			TInlineArray<SceneSyncFrameData, 4> SceneData;
		};

		void SyncRead(FrameAllocator* allocator);
		void SyncWrite();

		List<PerFrameSyncData> mPerFrameSyncData;
		Mutex mSyncDataMutex;
		FrameAllocator* mSyncAllocators[RenderThread::kSyncBufferCount + 1];
		u32 mActiveFrameAllocatorIndex = 0;
	};

	/** @} */
} // namespace b3d
