//************************************ B3D Framework - Copyright 2026 Marko Pintera **************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "B3DPrerequisites.h"
#include "Renderer/B3DRendererSyncManager.h"
#include "Renderer/B3DPackedSlotAllocator.h"

namespace b3d
{
	/** @addtogroup Renderer-Internal
	 *  @{
	 */

	/**
	 * Allocates slot IDs for renderer objects. Slots are guaranteed to result in packed array layout. Deallocating
	 * a slot can result in slot ID for an existing object to be changed, as the data is swapped with the deallocated slot.
	 *
	 * Implementers should assign the allocated slot to an ECS fragment on the provided ECS entity, and update swapped slot
	 * ECS fragment on deallocation (if any changed).
	 */
	class B3D_EXPORT IRendererObjectStorage
	{
	public:
		virtual ~IRendererObjectStorage() = default;

		/**
		 * Allocates a packed slot for the given entity.
		 *
		 * @note: Main thread only.
		 */
		virtual SlotId AllocateSlot(ecs::Entity entity) = 0;

		/**
		 * Deallocates the slot belonging to the given entity.
		 *
		 * @note: Main thread only.
		 */
		virtual void DeallocateSlot(ecs::Entity entity, ecs::Registry& registry) = 0;
	};

	/**
	 * Provides render thread storage for renderer objects, and synchronization of object data from the main thread into that storage.
	 *
	 * On the main thread renderer objects are represented as ECS entities, with ECS fragments for storing data. On the render thread the objects are stored
	 * in packed arrays referenced by slot IDs. Slot IDs are allocated from the main thread and stored on the ECS entity, and then used on the render thread
	 * to update the correct entry in the packed array.
	 *
	 * # Allocating slots
	 * Slot represents a single array entry in the packed arrays on the render thread. Slots should be allocated / deallocated from the main thread using
	 * AllocateSlot / DeallocateSlot. The allocated slot ID should be stored on the entity as a fragment of type @p SlotFragmentType.
	 *
	 * Since slot IDs are allocated/deallocated from the main thread, the render thread needs to be informed about those changes so it can update the slot IDs in its storage.
	 * This is done via UpdateSlotIds(), which replays the slot allocation/deallocation commands recorded by the main thread allocator on the render thread.
	 * This should be called during SyncWrite().
	 *
	 * # Syncing data
	 * Data should be synced from the main thread to the render thread using SyncRead / SyncWrite.
	 *  - SyncRead is called on the main thread, and should gather dirty data from ECS fragments associated with the entity into a batch buffer allocated by the provided allocator,
	 *    and return a pointer to that buffer.
	 *  - SyncWrite is called on the render thread with the batch buffer generated by SyncRead, and should apply the data to the render thread packed arrays using at the location of
	 *    the provided slot ID, then free the batch buffer using the provided allocator. SyncWrite must call UpdateSlotIds() before any operation to ensure the slot IDs in the
	 *    render thread storage are up to date with the main thread.
	 *
	 * @tparam SlotFragmentType	ECS fragment type that stores the packed ID (e.g. ecs::RenderableSlotId).
	 */
	template<typename SlotFragmentType>
	class TRendererObjectStorage : public IRendererObjectSyncHandler, public IRendererObjectStorage
	{
	public:
		SlotId AllocateSlot(ecs::Entity entity) override { return mAllocator.Allocate(entity); }
		void DeallocateSlot(ecs::Entity entity, ecs::Registry& registry) override { mAllocator.Deallocate(entity, registry); }

	protected:
		/** Replays slot allocate/deallocate commands on the render thread. */
		virtual void UpdateSlotIds(const SlotCommand* commands, u32 count) = 0;

		/** Consumes commands from the allocator and frame-allocates a copy. */
		u32 ConsumeAndAllocateCommands(FrameAllocator& allocator, SlotCommand*& outCommands)
		{
			const auto& commands = mAllocator.ConsumeCommands();
			u32 commandCount = (u32)commands.size();
			if(commandCount == 0)
			{
				outCommands = nullptr;
				return 0;
			}
			outCommands = reinterpret_cast<SlotCommand*>(allocator.AllocateAligned(sizeof(SlotCommand) * commandCount, alignof(SlotCommand)));
			memcpy(outCommands, commands.data(), sizeof(SlotCommand) * commandCount);
			return commandCount;
		}

		TPackedSlotAllocator<SlotFragmentType> mAllocator;
	};

	/** @} */
} // namespace b3d
