//************************************ bs::framework - Copyright 2018 Marko Pintera **************************************//
//*********** Licensed under the MIT license. See LICENSE.md for full terms. This notice is not to be removed. ***********//
#pragma once

#include "Prerequisites/BsPrerequisitesUtil.h"
#include "BsSerializedObject.h"

namespace bs
{
	class IRTTIIterator;
	struct RTTIIteratorField;
	/** @addtogroup Internal-Utility
	 *  @{
	 */

	/** @addtogroup Serialization-Internal
	 *  @{
	 */

	/**
	 * Represents an interface RTTI objects need to implement if they want to provide custom "diff" generation and applying.
	 */
	class B3D_UTILITY_EXPORT IDiff
	{
	public:
		virtual ~IDiff() = default;

		/**
		 * Generates per-field differences between the provided original and new object. Any field or array entry that is
		 * different in the new object compared to the original will be output in the resulting object, with a full
		 * hierarchy of that field.
		 *
		 * If @p replicableOnly true then only fields with replication enabled will be evaluated and all others will be
		 * ignored.
		 *
		 * You may compare a raw IReflectable object instance, or an object serialized as a SerializedObject. You can mix
		 * and match the two as long as their source types match.
		 *
		 * Will return null if there is no difference.
		 */
		SPtr<SerializedObject> GenerateDiff(const SPtr<IReflectable>& orgObj, const SPtr<IReflectable>& newObj, bool replicableOnly = false);

		/**
		 * Applies a previously generated per-field differences to the provided object. This will essentially transform the
		 * original object the differences were generated for into the modified version.
		 */
		void ApplyDiff(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff, SerializationContext* context);

		/**
		 * @name Internal
		 * @{
		 */

		typedef UnorderedMap<IReflectable*, SPtr<SerializedObject>> ObjectMap;

		/**
		 * Recursive version of GenerateDiff(const SPtr<IReflectable>&, const SPtr<IReflectable>&, bool).
		 *
		 * @see		GenerateDiff(const SPtr<IReflectable>&, const SPtr<IReflectable>&, bool)
		 */
		virtual SPtr<SerializedObject> GenerateDeltaRecursive(IReflectable* orgObj, IReflectable* newObj, ObjectMap& objectMap, bool replicableOnly) = 0;

		/** @} */

	protected:
		typedef UnorderedMap<SPtr<SerializedObject>, SPtr<IReflectable>> DeltaObjectMap;

		/** Types of commands that are used when applying difference field values. */
		enum DiffCommandType
		{
			Diff_Plain = 0x01,
			Diff_Reflectable = 0x02,
			Diff_ReflectablePtr = 0x03,
			Diff_DataBlock = 0x04,
			Diff_ArraySize = 0x05,
			Diff_ObjectStart = 0x06,
			Diff_ObjectEnd = 0x07,
			Diff_SubObjectStart = 0x08,
			Diff_IterableEntryStart = 0x09,
			Diff_IterableEntryEnd = 0x0A,
			Diff_ArrayFlag = 0x10,
			Diff_MapFlag = 0x20
		};

		/**
		 * A command that is used for delaying writing to an object, it contains all necessary information for setting RTTI
		 * field values on an object.
		 */
		struct DeltaCommand
		{
			RTTIField* Field;
			u32 Type;
			SPtr<IReflectable> Object;
			u8* Value;
			SPtr<DataStream> StreamValue;
			u32 Size;
			u32 TupleElementIndex = 0;

			union
			{
				u32 ArrayIndex;
				u32 ArraySize;
				RTTITypeBase* RttiType;
				void* MapKey;
			};
		};

		/**
		 * Recursive version of ApplyDiff(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff). Outputs a
		 * set of commands that then must be executed in order to actually apply the difference to the provided object.
		 *
		 * @see		ApplyDiff(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff)
		 */
		virtual void GenerateDeltaApplyCommands(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff, FrameAllocator& alloc, DeltaObjectMap& objectMap, FrameVector<DeltaCommand>& diffCommands, SerializationContext* context) = 0;

		/**
		 * Applies diff according to the diff handler retrieved from the provided RTTI object.
		 *
		 * @see		ApplyDiff(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff)
		 */
		void ApplyDiff(RTTITypeBase* rtti, const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff, FrameAllocator& alloc, DeltaObjectMap& objectMap, FrameVector<DeltaCommand>& diffCommands, SerializationContext* context);
	};

	/**
	 * Generates and applies "diffs". Diffs contain per-field differences between an original and new object. These
	 * differences can be saved and then applied to an original object to transform it to the new version.
	 *
	 * Any IReflectable object can have a diff generated, as well as objects in an intermediate serialized format
	 * generated by IntermediateSerializer.
	 */
	class B3D_UTILITY_EXPORT BinaryDiff : public IDiff
	{
	private:
		SPtr<SerializedObject> GenerateDeltaRecursive(IReflectable* lhs, IReflectable* rhs, ObjectMap& objectMap, bool replicableOnly) override;
		void GenerateDeltaApplyCommands(const SPtr<IReflectable>& object, const SPtr<SerializedObject>& diff, FrameAllocator& allocator, DeltaObjectMap& objectMap, FrameVector<DeltaCommand>& diffCommands, SerializationContext* context) override;

		/**
		 * Generates delta commands for a single field entry (e.g. a single array or map entry, or the entire field if not a container).
		 *
		 * @param rttiInstance		RTTIType instance for the current object.
		 * @param object			Object that contains the field we're applying the delta to.
		 * @param field				Field to which to apply the delta to.
		 * @param entryDelta		Object containing the delta value to apply.
		 * @param arrayIndex		Optional array index, if the entry we're applying the value to is part of an array. Set to ~0u if not an array.
		 * @param mapKey			Optional map key, if the entry we're applying the value to is part of a map. Set to null if not a map.
		 * @param inOutObjectMap	Map that contains any deserialized objects so far, and into which new deserialized objects will be inserted.
		 * @param outCommands		List of generated commands into which to output the commands.
		 * @param context			Serialization context.
		 * @param allocator			Allocator to perform temporary allocations with.
		 */
		void GenerateDeltaCommandForEntry(RTTITypeBase* rttiInstance, const SPtr<IReflectable>& object, RTTIIteratorField& field, const SPtr<ISerialized>& entryDelta, u32 arrayIndex, void* mapKey, DeltaObjectMap& inOutObjectMap, FrameVector<DeltaCommand>& outCommands, SerializationContext* context, FrameAllocator& allocator);

		// TODO - Doc
		void GenerateDeltaCommandForEntry(RTTITypeBase* rttiInstance, const SPtr<IReflectable>& object, RTTIField& field, const SPtr<ISerialized>& entryDelta, u32 arrayIndex, DeltaObjectMap& inOutObjectMap, FrameVector<DeltaCommand>& outCommands, SerializationContext* context, FrameAllocator& allocator); // DEPRECATED - Except the DataBlock case
	};

	/** @} */
	/** @} */
} // namespace bs
